logging: DEBUG
# OpenAI API token
token: ".env"
# max number of retries to get a valid mission plan from ChatGPT
max_retries: 10
# config for GPT
max_tokens: 4096
temperature: 0.2
# where to store results
log_directory: "./app/gpt_outputs/iros_experiments/4o"
# schema per 1872.1-2024 + farm layout
schema:
  - "schemas/schemas/clearpath_husky.xsd"
context_files:
  - "./app/resources/context/wheeled_bots/reza_small.geojson"
  # - "./app/resources/context/wheeled_bots/reza_medium.geojson"
  # - "app/resources/context/wheeled_bots/ucm_graph20.geojson"
# who to send this to?
host: 127.0.0.1
port: 12346
# LTL generation?
ltl: true
promela_template: "app/resources/context/formal_verification/promela_template.txt"
spin_path: "spin"
