logging:
  level: DEBUG

auth:
  token_env_file: ".env"

planner:
  retries:
    max: 10
  generation:
    max_tokens: 10000
    temperature: 0.2
  validation:
    lint_xml: true
    ltl_enabled: false
  formal_verification:
    promela_template: "app/resources/context/formal_verification/promela_template.txt"
    spin_path: "spin"

llm:
  routing:
    # supported modes: auto, online, offline
    mode: offline
    online_model: "openai/gpt-5.2"
    offline_model: "openai/openai/gpt-oss-20b"
  endpoints:
    online_api_base: null
    offline_api_base: "http://172.17.0.1:8000/v1"

mission:
  log_directory: "./app/gpt_outputs/tfr"
  schema_paths:
    - "schemas/amiga_btcpp.xsd"
  context_files:
    - "./app/resources/context/prompts/mission_planner/wheeled/orchard.j2"
  farm:
    polygon_file: "farm_polygons/reza_medium.yaml"

network:
  tcp:
    host: 172.17.0.1
    port: 12346
