logging: DEBUG
# OpenAI API token
token: "~/.gpt/token.env"
# max number of retries to get a valid mission plan from ChatGPT
max_retries: 2
max_tokens: 4000
temperature: 0.2
log_directory: "./app/gpt_outputs/"
# schema per 1872.1-2024 + farm layout
schema:
  - "schemas/schemas/bd_spot.xsd"
context_files:
  - "./app/resources/context/wheeled_bots/reza20.geojson"
# who to send this too?
host: 127.0.0.1
port: 12346
# LTL generation?
ltl: False
